project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('', include('simpeapp.urls')),
]

project/simpeapp/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django.core.cache import cache


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True, help_text=_('category name'))

    def __str__(self):
        return self.name.title()


class News(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
    )
    text = models.TextField()
    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    )
    categoryType = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default=ARTICLE,
    )
    dateCreation = models.DateTimeField(
        auto_now_add=True,
    )
    author = models.ForeignKey(
        to='Author',
        on_delete=models.CASCADE,
        related_name='products',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='products',
    )

    def __str__(self):
        return f'{self.name.title()}...: {self.text}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete(f'product-{self.pk}')


class PostCategory(models.Model):
    postThrough = models.ForeignKey(News, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Author(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name.title()


class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

project/templates/articles_edit.html
{% extends 'flatpages/default.html' %}
{% load i18n %}


{% load cache %}
{% cache 30 content %}
{% block content %}
        <h1>{% trans "Создайте свою статью" %}</h1>
        <hr>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save" />
        </form>
{% endblock content %}
{% endcache %}

project/templates/news_edit.html
{% extends 'flatpages/default.html' %}
{% load i18n %}

{% load cache %}
{% cache 30 content %}
{% block content %}
<form action="{% url 'set_language' %}" method="POST"> {% csrf_token %} <!-- Не забываем по csrf_token для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">
        {% get_current_language as LANGUAGE_CODE %}
        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->

            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
    </form>
<h1>{% trans "Создайте свою новость" %}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}
{% endcache %}

project/templates/post.html
{% extends 'flatpages/default.html' %}

{% block title %}
News
{% endblock title %}

{% load custom_filters %}
{% load cache %}
{% cache 30 content %}
{% block content %}
    <h1>{{ news.name|censor }}</h1>
    <hr>
    <P>
        <font size="5">{{ news.text|censor }}</font>
    </P>
    <P>
        <font size="4">{{ news.dateCreation|date:'d M Y' }}</font>
    </P>
{% endblock content %}
{% endcache %}

project/templates/posts.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load tz %}
{% block title %}
{% trans "News" %}
{% endblock title %}

{% load custom_filters %}
{% load custom_tags %}
{% load cache %}
{% cache 30 content %}
{% block content %}
        <form action="{% url 'set_language' %}" method="POST"> {% csrf_token %}
        <input type="hidden" name="next" value="{{ redirect_to }}">

        <select name="language" id="">
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}

            {% for language in languages %}
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %} >
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
    </form>
    {% get_current_timezone as TIME_ZONE %}
    <form action="" method="POST">
        {% csrf_token %}
        <label for="timezone">Time zone:</label>
        <select name="timezone">
            {% for tz in timezones %}
            <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Set">
    </form>

    {{ TIME_ZONE }}
    {{ current_time|timezone:TIME_ZONE }}

    <h1>Новости</h1>
    <hr>
    {% if perms.simpeapp.add_news %}
    <a href="{% url 'news_create' %}">Добавить товар</a>
    {% endif %}
    {% if news %}
        <div style="text-align: center;">
        <table cellpadding = '13' style="font-size: 20px;" >
            {% for post in news %}
            <tr>
            <tr>
                <td>{{ post.name|censor }}</td>
                <td>{{ post.dateCreation|date:'d M Y'  }}</td>
                <td>{{ post.text|truncatechars:20|censor }}</td>
                {% if perms.simpeapp.change_news or perms.simpeapp.delete_news %}
                <td>Действия
                    <br>
                {% endif %}
                {% if perms.simpeapp.change_news %}
                    <a href="{% url 'news_update' post.id %}">Изменить</a>
                    {% endif %}
                    {% if perms.simpeapp.delete_news %}
                    <a href="{% url 'news_delete' post.id %}">Удалить</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        </div>
    {% else %}
        <h2> Новостей нет </h2>
    {% endif %}

    {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}
{% endcache %}

project/templates/product_delete.html
{% extends 'flatpages/default.html' %}

{% load cache %}
{% cache 30 content %}
{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}
{% endcache %}

project/templates/search.html
{% extends 'flatpages/default.html' %}
{% block title %}
News
{% endblock title %}

{% load custom_filters %}
{% load custom_tags %}
{% load cache %}
{% load i18n %}

{% cache 30 content %}
{% block content %}
    <form action="{% url 'set_language' %}" method="POST"> {% csrf_token %} <!-- Не забываем по csrf_token для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">
            {% get_current_language as LANGUAGE_CODE %}
        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->

            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
    </form>
    <h1>{% trans "Поиск" %}</h1>
    <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>
    {% if news %}
        <div style="text-align: center;">
        <table cellpadding = '13' style="font-size: 20px;" >
            {% for post in news %}
            <tr>
                <td>{{ post.name|censor }}</td>
                <td>{{ post.dateCreation|date:'d M Y'  }}</td>
                <td>{{ post.text|truncatechars:20|censor }}</td>
                {% if perms.simpeapp.change_news or perms.simpeapp.delete_news %}
                <td>{% trans "Действия" %}
                    <br>
                {% endif %}
                {% if perms.simpeapp.change_news %}
                    <a href="{% url 'news_update' post.id %}">{% trans "Изменить" %}</a>
                    {% endif %}
                    {% if perms.simpeapp.delete_news %}
                    <a href="{% url 'news_delete' post.id %}">{% trans "Удалить" %}</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        </div>
    {% else %}
        <h2> Новостей нет </h2>
    {% endif %}

    {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}
{% endcache %}

project/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% load cache %}
{% cache 30 content %}
{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}
{% endcache %}